//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelSovetApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appeal
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> ResultId { get; set; }
        public System.DateTime DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public int ClientId { get; set; }
        public string Text { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Result Result { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
